name: Test and Merge Clash Configs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */2 * * *'  # 每两个小时执行一次
  workflow_dispatch:

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install pyyaml requests clashmeta-launcher yq

      - name: Create Temp Dir and Time Vars
        id: create_tmp
        run: |
          tmpdir=$(mktemp -d)
          date_short=$(date '+%Y%m%d')
          echo "tmpdir=$tmpdir" >> "$GITHUB_OUTPUT"
          echo "date_short=$date_short" >> "$GITHUB_OUTPUT"

      - name: Download Config List
        id: download_list
        run: |
          curl -s -o config-list.txt https://raw.githubusercontent.com/${{ github.repository }}/main/config-list.txt
          echo "✅ Downloaded config-list.txt:"
          cat config-list.txt

      - name: Download YAML Files
        id: download_files
        run: |
          tmpdir="${{ steps.create_tmp.outputs.tmpdir }}"
          while IFS= read -r url; do
            [ -z "$url" ] && continue
            filename=$(basename "$url")
            curl -s -o "$tmpdir/$filename" "$url"
            echo "Downloaded $filename"
          done < config-list.txt

      - name: Test Proxies & Merge Valid Ones
        run: |
          TMP_DIR="${{ steps.create_tmp.outputs.tmpdir }}"

          cat > "$TMP_DIR/template.yaml" << EOL
# Merged Clash Config
proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - DIRECT
rules:
  - MATCH,Proxy
EOL

          valid_proxies=()

          for file in "$TMP_DIR"/*.yaml; do
            echo "=== Testing config: $file ==="

            proxy_name=$(grep -A 1 '^proxies:' "$file" | grep 'name:' | head -n1 | awk '{print $2}' | tr -d '"')
            if [ -z "$proxy_name" ]; then
              proxy_name="Proxy-$(basename "$file")"
            fi

            cp "$file" "$TMP_DIR/config.yaml"

            clashmeta -f "$TMP_DIR/config.yaml" -d "$TMP_DIR" &
            clash_pid=$!
            sleep 10

            export http_proxy="http://127.0.0.1:7890"
            export https_proxy="http://127.0.0.1:7890"

            if curl -I --silent --connect-timeout 10 https://www.google.com | grep -q "200 OK"; then
              echo "✅ Proxy in $file works."
              valid_proxies+=("$proxy_name")
              yq e ".proxies[] | select(.name == \"$proxy_name\")" "$TMP_DIR/config.yaml" >> "$TMP_DIR/proxies.yaml"
            else
              echo "❌ Proxy in $file does NOT work."
            fi

            kill $clash_pid || true
            sleep 2
          done

          cat "$TMP_DIR/template.yaml" > merged-config.yaml
          if [ -f "$TMP_DIR/proxies.yaml" ]; then
            echo "proxies:" >> merged-config.yaml
            cat "$TMP_DIR/proxies.yaml" >> merged-config.yaml

            echo "  - name: Proxy" >> merged-config.yaml
            echo "    type: select" >> merged-config.yaml
            echo "    proxies:" >> merged-config.yaml

            for name in "${valid_proxies[@]}"; do
              echo "      - $name" >> merged-config.yaml
            done
          else
            echo "proxies: []" >> merged-config.yaml
          fi

          echo "✅ Final merged config saved to merged-config.yaml"
          cat merged-config.yaml

      - name: Commit and Push Merged Config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add merged-config.yaml
          git commit -m "Update merged clash config $(date '+%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
